### ISSUE TITLE
[Bug] Spinner component CSS/SCSS missing

### ISSUE THREAD

**Issue by anchowake** [creativetimofficial/ct-argon-dashboard-pro-react#15]
### Version
1.0.0
### Reproduction link
N/A
### Operating System
macOS Catalina
### Device
MBP
### Browser & Version
Chrome Version 79.0.3945.130 (Official Build) (64-bit)
### Steps to reproduce
1.- Create ``` <Spinner>``` component
2.- The component doesn't render because of missing CSS classes
### What is expected?
https://getbootstrap.com/docs/4.3/components/spinners/
### What is actually happening?
Spinner class does not exist on the src files.

---
### Solution
Add manually the CSS to my files.
```css
@keyframes spinner-border {
  to {transform: rotate(360deg);}
}

@keyframes spinner-grow {
  0% {
   -webkit-transform:scale(0);
   transform:scale(0)
  }
  50% {
   opacity:1
  }
 }

.spinner-border {
  display: inline-block;
  width: 2rem;
  height: 2rem;
  vertical-align: text-bottom;
  border: .25em solid currentColor;
  border-right-color: transparent;
  border-radius: 50%;
  -webkit-animation: spinner-border .75s linear infinite;
  animation: spinner-border 1s linear infinite;
}

.spinner-grow {
  display: inline-block;
  width: 2rem;
  height: 2rem;
  vertical-align: text-bottom;
  background-color: currentColor;
  border-radius: 50%;
  opacity: 0;
  -webkit-animation: spinner-grow .75s linear infinite;
  animation: spinner-grow .75s linear infinite;
}
```

### Additional comments

Variant colors aren't working either
